name: study_room_sdk
description: Core Flutter SDK for integrating online study rooms.
version: 0.4.0-rc.1
homepage: https://github.com/qssn70/study_room_sdk
repository: https://github.com/qssn70/study_room_sdk
issue_tracker: https://github.com/qssn70/study_room_sdk/issues
topics:
  - flutter
  - realtime
  - study
  - collaboration

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  http: ^1.6.0
  socket_io_client: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
