import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'generated/l10n/study_room_localizations.dart';
import 'generated/l10n/study_room_localizations_en.dart';

// Generated by tool/generate_localizations_compat.dart.
// Do not edit by hand.
class StudyRoomLocalizations
    extends GeneratedStudyRoomLocalizations {
  factory StudyRoomLocalizations(Locale locale) {
    final resolved = locale.languageCode == 'zh'
        ? const Locale('zh')
        : const Locale('en');
    return StudyRoomLocalizations._(
      lookupGeneratedStudyRoomLocalizations(resolved),
      resolved,
    );
  }

  StudyRoomLocalizations._(this._delegate, this.locale)
    : super(_delegate.localeName);

  final GeneratedStudyRoomLocalizations _delegate;
  final Locale locale;

  static StudyRoomLocalizations of(BuildContext context) {
    final value = maybeOf(context);
    assert(
      value != null,
      'StudyRoomLocalizations is not available in this context',
    );
    return value ??
        StudyRoomLocalizations._(
          GeneratedStudyRoomLocalizationsEn(),
          const Locale('en'),
        );
  }

  static StudyRoomLocalizations? maybeOf(BuildContext context) =>
      Localizations.of<StudyRoomLocalizations>(
        context,
        StudyRoomLocalizations,
      );

  static const delegate = _StudyRoomLocalizationsDelegate();
  static const supportedLocales =
      GeneratedStudyRoomLocalizations.supportedLocales;
  static const localizationsDelegates = <LocalizationsDelegate<dynamic>>[
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  @override
  String get rooms => _delegate.rooms;

  @override
  String get createRoom => _delegate.createRoom;

  @override
  String get roomTitle => _delegate.roomTitle;

  @override
  String get joinRoom => _delegate.joinRoom;

  @override
  String get roomId => _delegate.roomId;

  @override
  String get pendingRequests => _delegate.pendingRequests;

  @override
  String get myRequests => _delegate.myRequests;

  @override
  String get approve => _delegate.approve;

  @override
  String get reject => _delegate.reject;

  @override
  String get cancel => _delegate.cancel;

  @override
  String get members => _delegate.members;

  @override
  String get transferOwnership => _delegate.transferOwnership;

  @override
  String get remove => _delegate.remove;

  @override
  String get retry => _delegate.retry;

  @override
  String get refresh => _delegate.refresh;

  @override
  String get noRooms => _delegate.noRooms;

  @override
  String get noRequests => _delegate.noRequests;

  @override
  String get open => _delegate.open;

  @override
  String get owner => _delegate.owner;

  @override
  String get member => _delegate.member;

  @override
  String get pending => _delegate.pending;

  @override
  String get approved => _delegate.approved;

  @override
  String get rejected => _delegate.rejected;

  @override
  String get cancelled => _delegate.cancelled;

  @override
  String get requestSubmitted => _delegate.requestSubmitted;

  @override
  String get operationFailed => _delegate.operationFailed;

  @override
  String get emptyMembers => _delegate.emptyMembers;

  @override
  String get emptyMessages => _delegate.emptyMessages;

  @override
  String get reconnecting => _delegate.reconnecting;

  @override
  String get connected => _delegate.connected;

  @override
  String get presenceFocusing => _delegate.presenceFocusing;

  @override
  String get presenceOnline => _delegate.presenceOnline;

  @override
  String get presenceIdle => _delegate.presenceIdle;

  @override
  String get presenceAway => _delegate.presenceAway;

  @override
  String get presenceOffline => _delegate.presenceOffline;

  @override
  String get noCompanions => _delegate.noCompanions;

  @override
  String get start => _delegate.start;

  @override
  String get play => _delegate.play;

  @override
  String get pause => _delegate.pause;

  @override
  String get resume => _delegate.resume;

  @override
  String get finish => _delegate.finish;

  @override
  String get messageHint => _delegate.messageHint;

  @override
  String get send => _delegate.send;

  @override
  String get localDataLoadFailed => _delegate.localDataLoadFailed;

  @override
  String get focusAppTitle => _delegate.focusAppTitle;

  @override
  String get focusSection => _delegate.focusSection;

  @override
  String get analyticsSection => _delegate.analyticsSection;

  @override
  String get historySection => _delegate.historySection;

  @override
  String get settingsSection => _delegate.settingsSection;

  @override
  String get newTask => _delegate.newTask;

  @override
  String get editTask => _delegate.editTask;

  @override
  String get endCurrentRound => _delegate.endCurrentRound;

  @override
  String get skipToBreak => _delegate.skipToBreak;

  @override
  String get defaultGoal => _delegate.defaultGoal;

  @override
  String get goalSaveFailed => _delegate.goalSaveFailed;

  @override
  String get noTasks => _delegate.noTasks;

  @override
  String get edit => _delegate.edit;

  @override
  String get delete => _delegate.delete;

  @override
  String get deleteTaskTitle => _delegate.deleteTaskTitle;

  @override
  String get taskDeleteFailed => _delegate.taskDeleteFailed;

  @override
  String get taskSaveFailed => _delegate.taskSaveFailed;

  @override
  String get save => _delegate.save;

  @override
  String get taskName => _delegate.taskName;

  @override
  String get taskNameRequired => _delegate.taskNameRequired;

  @override
  String get background => _delegate.background;

  @override
  String get defaultBackground => _delegate.defaultBackground;

  @override
  String get silentCompanions => _delegate.silentCompanions;

  @override
  String get whiteNoise => _delegate.whiteNoise;

  @override
  String get todayPrivateData => _delegate.todayPrivateData;

  @override
  String get customDuration => _delegate.customDuration;

  @override
  String get custom => _delegate.custom;

  @override
  String get focusMinutes => _delegate.focusMinutes;

  @override
  String get breakMinutes => _delegate.breakMinutes;

  @override
  String get apply => _delegate.apply;

  @override
  String get pomodoroDurationInvalid => _delegate.pomodoroDurationInvalid;

  @override
  String get saveFailed => _delegate.saveFailed;

  @override
  String get pomodoroReady => _delegate.pomodoroReady;

  @override
  String get pomodoroFocusing => _delegate.pomodoroFocusing;

  @override
  String get pomodoroPaused => _delegate.pomodoroPaused;

  @override
  String get pomodoroBreaking => _delegate.pomodoroBreaking;

  @override
  String get pomodoroFinished => _delegate.pomodoroFinished;

  @override
  String get skip => _delegate.skip;

  @override
  String get todayGoal => _delegate.todayGoal;

  @override
  String get backgroundSound => _delegate.backgroundSound;

  @override
  String get privateStats => _delegate.privateStats;

  @override
  String get companions => _delegate.companions;

  @override
  String get todayFocus => _delegate.todayFocus;

  @override
  String get todayPomodoros => _delegate.todayPomodoros;

  @override
  String get streak => _delegate.streak;

  @override
  String get stats => _delegate.stats;

  @override
  String get soundRain => _delegate.soundRain;

  @override
  String get soundWhiteNoise => _delegate.soundWhiteNoise;

  @override
  String get soundCafe => _delegate.soundCafe;

  @override
  String get soundLibrary => _delegate.soundLibrary;

  @override
  String get soundKeyboard => _delegate.soundKeyboard;

  @override
  String get backgroundMidnight => _delegate.backgroundMidnight;

  @override
  String get backgroundForest => _delegate.backgroundForest;

  @override
  String get unableToSaveFocusSession => _delegate.unableToSaveFocusSession;

  @override
  String get todayGoalLabel => _delegate.todayGoalLabel;

  @override
  String get targetPomodoros => _delegate.targetPomodoros;

  @override
  String get analyticsFocus => _delegate.analyticsFocus;

  @override
  String get analyticsPomodoros => _delegate.analyticsPomodoros;

  @override
  String get analyticsStreak => _delegate.analyticsStreak;

  @override
  String get analyticsToday => _delegate.analyticsToday;

  @override
  String get analyticsCount => _delegate.analyticsCount;

  @override
  String get analyticsRun => _delegate.analyticsRun;

  @override
  String get analyticsTotal => _delegate.analyticsTotal;

  @override
  String get analyticsSessions => _delegate.analyticsSessions;

  @override
  String get analyticsTasks => _delegate.analyticsTasks;

  @override
  String get noTasksReport => _delegate.noTasksReport;

  @override
  String get reportNoFocusSessions => _delegate.reportNoFocusSessions;

  @override
  String onlineMemberCount(int count) => _delegate.onlineMemberCount(count);

  @override
  String memberCount(int count) => _delegate.memberCount(count);

  @override
  String pomodoroProgressRemaining(int done, int target, int minutes) => _delegate.pomodoroProgressRemaining(done, target, minutes);

  @override
  String pomodoroProgress(int done, int target) => _delegate.pomodoroProgress(done, target);

  @override
  String completionPercent(int percent) => _delegate.completionPercent(percent);

  @override
  String focusHistorySummary(int minutes, int count) => _delegate.focusHistorySummary(minutes, count);

  @override
  String tasksForDate(String date) => _delegate.tasksForDate(date);

  @override
  String deleteTaskConfirmation(String title) => _delegate.deleteTaskConfirmation(title);

  @override
  String backgroundMask(int percent) => _delegate.backgroundMask(percent);

  @override
  String pomodoroPresetMinutes(int focus, int rest) => _delegate.pomodoroPresetMinutes(focus, rest);

  @override
  String pomodoroCountValue(int count) => _delegate.pomodoroCountValue(count);

  @override
  String dayCountValue(int count) => _delegate.dayCountValue(count);

  @override
  String hoursValue(String value) => _delegate.hoursValue(value);

  @override
  String minutesValue(int count) => _delegate.minutesValue(count);

  @override
  String daysValue(int count) => _delegate.daysValue(count);

  @override
  String pomodorosValue(int count) => _delegate.pomodorosValue(count);

  @override
  String completionValue(int percent) => _delegate.completionValue(percent);

  @override
  String reportSummary(int minutes, int pomodoros, int streak) => _delegate.reportSummary(minutes, pomodoros, streak);

}

class _StudyRoomLocalizationsDelegate
    extends LocalizationsDelegate<StudyRoomLocalizations> {
  const _StudyRoomLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      GeneratedStudyRoomLocalizations.delegate.isSupported(locale);

  @override
  Future<StudyRoomLocalizations> load(Locale locale) {
    return SynchronousFuture<StudyRoomLocalizations>(
      StudyRoomLocalizations._(
        lookupGeneratedStudyRoomLocalizations(locale),
        locale,
      ),
    );
  }

  @override
  bool shouldReload(_StudyRoomLocalizationsDelegate old) => false;
}

StudyRoomLocalizations studyRoomLocalizationsOf(BuildContext context) =>
    StudyRoomLocalizations.maybeOf(context) ??
    StudyRoomLocalizations._(
      GeneratedStudyRoomLocalizationsEn(),
      const Locale('en'),
    );
