import 'dart:io';

void main() {
  final generated = File(
    'lib/src/generated/l10n/study_room_localizations.dart',
  );
  final output = File('lib/src/localizations_compat.dart');
  final getters = <String>[];
  final methods = <(String, String)>[];
  final getterPattern = RegExp(r'^  String get ([A-Za-z0-9_]+);$');
  final methodPattern = RegExp(r'^  String ([A-Za-z0-9_]+)\((.*)\);$');

  for (final line in generated.readAsLinesSync()) {
    final getter = getterPattern.firstMatch(line);
    if (getter != null) {
      getters.add(getter.group(1)!);
      continue;
    }
    final method = methodPattern.firstMatch(line);
    if (method != null) {
      methods.add((method.group(1)!, method.group(2)!));
    }
  }

  final buffer = StringBuffer()
    ..writeln("import 'package:flutter/foundation.dart';")
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln(
      "import 'package:flutter_localizations/flutter_localizations.dart';",
    )
    ..writeln()
    ..writeln("import 'generated/l10n/study_room_localizations.dart';")
    ..writeln("import 'generated/l10n/study_room_localizations_en.dart';")
    ..writeln()
    ..writeln('// Generated by tool/generate_localizations_compat.dart.')
    ..writeln('// Do not edit by hand.')
    ..writeln('class StudyRoomLocalizations')
    ..writeln('    extends GeneratedStudyRoomLocalizations {')
    ..writeln('  factory StudyRoomLocalizations(Locale locale) {')
    ..writeln("    final resolved = locale.languageCode == 'zh'")
    ..writeln("        ? const Locale('zh')")
    ..writeln("        : const Locale('en');")
    ..writeln('    return StudyRoomLocalizations._(')
    ..writeln('      lookupGeneratedStudyRoomLocalizations(resolved),')
    ..writeln('      resolved,')
    ..writeln('    );')
    ..writeln('  }')
    ..writeln()
    ..writeln('  StudyRoomLocalizations._(this._delegate, this.locale)')
    ..writeln('    : super(_delegate.localeName);')
    ..writeln()
    ..writeln('  final GeneratedStudyRoomLocalizations _delegate;')
    ..writeln('  final Locale locale;')
    ..writeln()
    ..writeln('  static StudyRoomLocalizations of(BuildContext context) {')
    ..writeln('    final value = maybeOf(context);')
    ..writeln('    assert(')
    ..writeln('      value != null,')
    ..writeln(
      "      'StudyRoomLocalizations is not available in this context',",
    )
    ..writeln('    );')
    ..writeln('    return value ??')
    ..writeln('        StudyRoomLocalizations._(')
    ..writeln('          GeneratedStudyRoomLocalizationsEn(),')
    ..writeln("          const Locale('en'),")
    ..writeln('        );')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  static StudyRoomLocalizations? maybeOf(BuildContext context) =>',
    )
    ..writeln('      Localizations.of<StudyRoomLocalizations>(')
    ..writeln('        context,')
    ..writeln('        StudyRoomLocalizations,')
    ..writeln('      );')
    ..writeln()
    ..writeln('  static const delegate = _StudyRoomLocalizationsDelegate();')
    ..writeln('  static const supportedLocales =')
    ..writeln('      GeneratedStudyRoomLocalizations.supportedLocales;')
    ..writeln(
      '  static const localizationsDelegates = <LocalizationsDelegate<dynamic>>[',
    )
    ..writeln('    delegate,')
    ..writeln('    GlobalMaterialLocalizations.delegate,')
    ..writeln('    GlobalCupertinoLocalizations.delegate,')
    ..writeln('    GlobalWidgetsLocalizations.delegate,')
    ..writeln('  ];')
    ..writeln();

  for (final name in getters) {
    buffer
      ..writeln('  @override')
      ..writeln('  String get $name => _delegate.$name;')
      ..writeln();
  }
  for (final (name, parameters) in methods) {
    final arguments = parameters
        .split(',')
        .map((parameter) => parameter.trim().split(RegExp(r'\s+')).last)
        .join(', ');
    buffer
      ..writeln('  @override')
      ..writeln('  String $name($parameters) => _delegate.$name($arguments);')
      ..writeln();
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('class _StudyRoomLocalizationsDelegate')
    ..writeln('    extends LocalizationsDelegate<StudyRoomLocalizations> {')
    ..writeln('  const _StudyRoomLocalizationsDelegate();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  bool isSupported(Locale locale) =>')
    ..writeln(
      '      GeneratedStudyRoomLocalizations.delegate.isSupported(locale);',
    )
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Future<StudyRoomLocalizations> load(Locale locale) {')
    ..writeln('    return SynchronousFuture<StudyRoomLocalizations>(')
    ..writeln('      StudyRoomLocalizations._(')
    ..writeln('        lookupGeneratedStudyRoomLocalizations(locale),')
    ..writeln('        locale,')
    ..writeln('      ),')
    ..writeln('    );')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln(
      '  bool shouldReload(_StudyRoomLocalizationsDelegate old) => false;',
    )
    ..writeln('}')
    ..writeln()
    ..writeln(
      'StudyRoomLocalizations studyRoomLocalizationsOf(BuildContext context) =>',
    )
    ..writeln('    StudyRoomLocalizations.maybeOf(context) ??')
    ..writeln('    StudyRoomLocalizations._(')
    ..writeln('      GeneratedStudyRoomLocalizationsEn(),')
    ..writeln("      const Locale('en'),")
    ..writeln('    );');

  output.writeAsStringSync(buffer.toString());
}
